name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # runs once a day
  workflow_dispatch:       # allows manual run from the Actions tab
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake animation
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#8300FF&color_dots=#ebedf0,#d8b4fe,#c084fc,#a855f7,#8300FF
            dist/github-contribution-grid-snake-dark.svg?color_snake=#A855F7&color_dots=#161b22,#4c1d95,#6d28d9,#8300FF,#A855F7

      - name: Push snake svg to the output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
